name: Check compilation

on:
  push:

jobs:
  fivem:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: docker build .